In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("~/Desktop/NCSA_genomics/Healthy_volunteer_example_data_FreeStyle_Libre.txt", sep="\t")

In [7]:
data

,ID,Time,Record Type,Historic Glucose (mmol/L),Scan Glucose (mmol/L),Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Non-numeric Long-Acting Insulin,Long-Acting Insulin (units),Notes,Strip Glucose (mmol/L),Ketone (mmol/L),Meal Insulin (units),Correction Insulin (units),User Change Insulin (units),Previous Time,Updated Time
0,85,2019/02/21 13:57,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019/02/21 13:55,2019/02/21 13:57
1,90,2019/02/21 14:59,1,NaN,5.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,94,2019/02/21 15:36,1,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,98,2019/02/21 16:04,1,NaN,4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,102,2019/02/21 16:33,1,NaN,4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,16143047311241596053,2019/03/07 05:48,0,4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1466,16143047311241596068,2019/03/07 06:03,0,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1467,16143047311241596083,2019/03/07 06:18,0,4.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1468,16143047311241596098,2019/03/07 06:33,0,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1469,16143047311241596113,2019/03/07 06:48,0,4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN