In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings  
warnings.filterwarnings('ignore')

from TSForecasting.TsForecasting import TimeSeriesForecast

from TSForecasting.mage_calc import MageDataSet

Using TensorFlow backend.

In [2]:
data = pd.read_csv("~/Desktop/NCSA_genomics/Python - notebooks/TSForecasting/Data/consolidatedDataForPackage.csv")
print(data.dtypes)
data.head()

Display Time     object
GlucoseValue    float64
subjectId        object
dtype: object

          Display Time  GlucoseValue subjectId
0  2016-06-21 00:00:00         197.0     GVP01
1  2016-06-21 00:15:00         208.0     GVP01
2  2016-06-21 00:30:00         226.0     GVP01
3  2016-06-21 00:45:00         241.0     GVP01
4  2016-06-21 01:00:00         250.0     GVP01

In [3]:
obj = TimeSeriesForecast()

Object Created!

In [4]:
obj.gvIndices(data)

,GFI,GCF,LBGI,HBGI,BGRI,GRADE,HypoG_P,EuG_P,HyperG_P,J Index,...,MAX,MIN,HBA1C,MEAN,STD-DEV,CV,IQR,SDRC,PGS,dt
Subject ID,,,,,,,,,,,,,,,,,,,,,
1636-69-001,3.640,0.036,1.573,0.676,2.249,192.020,0.796,90.451,8.753,16.735,...,225.0,68.0,5.188,102.183,27.181,0.266,20.0,0.728,9.014,1788.0
1636-69-001-2,4.598,0.041,0.891,0.808,1.699,195.257,0.366,86.264,13.370,19.317,...,250.0,64.0,5.544,112.403,26.583,0.236,29.0,0.912,7.919,3265.0
1636-69-026,4.766,0.041,0.367,0.612,0.979,196.423,0.167,86.526,13.307,18.301,...,182.0,62.0,5.640,115.156,20.124,0.175,24.0,0.806,7.184,5147.0
1636-69-028,3.841,0.035,0.598,0.334,0.932,194.940,0.000,93.519,6.481,16.349,...,168.0,75.0,5.457,109.925,17.936,0.163,26.0,0.750,5.349,3864.0
1636-69-032,4.254,0.039,0.548,0.196,0.744,194.566,0.056,97.027,2.916,15.268,...,191.0,67.0,5.401,108.316,15.249,0.141,19.0,0.850,6.204,5189.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
OD575,7.849,0.055,1.843,5.130,6.973,200.727,8.132,48.315,43.553,40.820,...,400.0,40.0,6.567,141.773,60.265,0.425,76.0,1.189,18.590,49211.0
OD584,9.166,0.048,0.241,12.059,12.300,211.656,0.881,21.333,77.786,66.525,...,400.0,40.0,8.334,192.484,65.440,0.340,85.0,1.488,30.193,59727.0
OD588,6.534,0.040,0.341,7.125,7.466,207.000,0.949,33.655,65.396,46.439,...,400.0,40.0,7.376,164.988,50.508,0.306,72.0,1.254,23.950,52594.0
OD591,8.448,0.054,1.058,6.624,7.682,204.339,3.697,40.739,55.564,45.822,...,397.0,40.0,7.063,156.022,58.040,0.372,84.0,1.336,22.058,50250.0
OD596,6.244,0.042,0.672,4.919,5.591,203.031,1.894,48.534,49.572,38.608,...,367.0,40.0,6.756,147.194,49.296,0.335,69.0,1.022,18.057,36666.0

In [5]:
data_fullDays = obj.fullDaysOnly(data)
data_fullDays.head()

         Display Time  GlucoseValue    subjectId
0 2014-02-04 00:02:07          88.0  1636-69-001
1 2014-02-04 00:07:07          87.0  1636-69-001
2 2014-02-04 00:12:07          87.0  1636-69-001
3 2014-02-04 00:17:07          91.0  1636-69-001
4 2014-02-04 00:22:07          93.0  1636-69-001

In [6]:
obj.gvIndices(data_fullDays)

,GFI,GCF,LBGI,HBGI,BGRI,GRADE,HypoG_P,EuG_P,HyperG_P,J Index,...,MAX,MIN,HBA1C,MEAN,STD-DEV,CV,IQR,SDRC,PGS,dt
Subject ID,,,,,,,,,,,,,,,,,,,,,
1636-69-001,4.608,0.043,1.515,1.229,2.745,193.197,0.000,86.411,13.589,20.041,...,225.0,70.0,5.364,107.251,34.314,0.320,27.5,0.923,5.950,871.0
1636-69-001-2,4.217,0.037,0.477,0.660,1.136,196.315,0.122,85.924,13.953,18.621,...,181.0,64.0,5.636,115.045,21.412,0.186,27.0,0.835,6.134,2351.0
1636-69-026,4.885,0.042,0.362,0.598,0.959,196.521,0.201,86.738,13.061,18.291,...,182.0,62.0,5.650,115.455,19.789,0.171,25.0,0.803,7.163,4254.0
1636-69-028,3.892,0.036,0.638,0.290,0.928,194.571,0.000,93.727,6.273,15.909,...,168.0,75.0,5.413,108.650,17.479,0.161,24.0,0.763,5.388,3417.0
1636-69-032,4.033,0.038,0.603,0.141,0.744,194.183,0.069,97.637,2.293,14.717,...,156.0,67.0,5.355,106.989,14.323,0.134,19.0,0.805,6.134,3986.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
OD575,7.654,0.054,1.829,4.873,6.702,200.544,7.986,48.811,43.203,39.532,...,400.0,40.0,6.523,140.504,58.323,0.415,74.0,1.175,18.278,47162.0
OD584,9.238,0.048,0.228,11.908,12.135,211.512,0.812,21.838,77.350,66.165,...,400.0,40.0,8.305,191.650,65.575,0.342,84.0,1.486,29.941,56562.0
OD588,6.561,0.040,0.335,7.192,7.527,207.145,0.983,33.017,66.000,46.630,...,400.0,40.0,7.398,165.613,50.328,0.304,71.0,1.258,24.144,50891.0
OD591,8.490,0.054,1.051,6.686,7.737,204.433,3.656,40.598,55.746,46.063,...,397.0,40.0,7.079,156.469,58.155,0.372,84.0,1.333,22.179,48361.0
OD596,6.322,0.043,0.673,5.000,5.672,203.088,1.915,48.466,49.619,38.937,...,367.0,40.0,6.769,147.571,49.755,0.337,70.0,1.031,18.187,35700.0