In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime
from statistics import mean
from datetime import timedelta

import math

import warnings  
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("~/Desktop/NCSA_genomics/prediabetic.csv")
data['DisplayTime'] = pd.to_datetime(data['DisplayTime'])
data['GlucoseValue'] = pd.to_numeric(data['GlucoseValue'])

In [3]:
def fullDay(data):
        
    dates = list()
    data = data.reset_index(drop=True)
    for i in range(0,len(data.index)):
        dates.append(data['DisplayTime'][i].date())
    data['Dates'] = dates
    end = data['Dates'].iloc[-1]
    start = data['Dates'].iloc[0]

    indexVals = data[ data['Dates'] == start ].index
    # indexVals
    data.drop(indexVals , inplace=True)

    indexVals = data[ data['Dates'] == end ].index
    # indexVals
    data.drop(indexVals , inplace=True)

    data = data.reset_index(drop=True)

    data.drop(['Dates'], axis=1, inplace=True)

    return data

In [4]:
def subSample(data):
    data = data.reset_index(drop=True)
    data['DisplayTime'] = pd.to_datetime(data['DisplayTime'])
    data['time_gap'] = data['DisplayTime'].shift(1)-data['DisplayTime'][0]
    data['time_gap'][0] = '00:00:00'
    mods = [0,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899]
    subset = pd.DataFrame()
    for i in range(1,len(data.index)):
        seconds = data['time_gap'][i].total_seconds()
        if (seconds%900) in mods:
            subj_id = data['subjectId'][i]
            gv = data['GlucoseValue'][i]
            dt = data['DisplayTime'][i]
            temp_df = pd.DataFrame({'Display Time':[dt], 'GlucoseValue':[gv], 'subjectId':[subj_id]})
            subset = pd.concat([temp_df,subset],ignore_index=True)
    subset = subset.iloc[::-1]
    subset = subset.reset_index(drop=True)
    data.drop(['time_gap'], axis=1, inplace=True)
    return subset

In [5]:
def modd(data):
    data['DisplayTime'] = data['DisplayTime'].dt.round('5min') 
    
    times = []
    for i in range(len(data.index)):
        times.append(data['DisplayTime'][i].time())
    data['Time'] = times  


    Modd = [] 
    s = 0
    gvDiff = 0

    for Time, df in data.groupby('Time'):
        gvDiff = df['GlucoseValue'] - df['GlucoseValue'].shift(-1)
        s = round(gvDiff.sum(),3)
        Modd.append(s)
    return round(mean(Modd),3)

In [6]:
# for subjectId, df in data.groupby('subjectId'):
#     df = fullDay(df)
#     df = subSample(df)
#     modd_value = modd(df)
#     print(subjectId, modd_value)

In [7]:
xx = data[data['subjectId'] == "1636-69-032"]
# xx = fullDay(xx)
# xx = subSample(xx)
print(modd(xx))

4.42

In [68]:
xx['DisplayTime'] = xx['DisplayTime'].dt.round('5min') 
dates = []
times = []
for i in range(len(xx.index)):
    dates.append(xx['DisplayTime'][i].date())
    times.append(xx['DisplayTime'][i].time())
xx['Date'] = dates   
xx['Time'] = times
xx

          Display Time  GlucoseValue subjectId        Date      Time
0  2018-08-02 00:15:00          81.0      ID32  2018-08-02  00:15:00
1  2018-08-02 00:30:00          79.0      ID32  2018-08-02  00:30:00
2  2018-08-02 00:45:00          81.0      ID32  2018-08-02  00:45:00
3  2018-08-02 01:00:00          86.0      ID32  2018-08-02  01:00:00
4  2018-08-02 01:15:00          88.0      ID32  2018-08-02  01:15:00
5  2018-08-02 01:30:00          89.0      ID32  2018-08-02  01:30:00
6  2018-08-02 01:45:00          82.0      ID32  2018-08-02  01:45:00
7  2018-08-02 02:00:00          92.0      ID32  2018-08-02  02:00:00
8  2018-08-02 02:15:00          93.0      ID32  2018-08-02  02:15:00
9  2018-08-02 02:30:00          96.0      ID32  2018-08-02  02:30:00
10 2018-08-02 02:45:00          88.0      ID32  2018-08-02  02:45:00
11 2018-08-02 03:00:00          88.0      ID32  2018-08-02  03:00:00
12 2018-08-02 03:15:00          87.0      ID32  2018-08-02  03:15:00
13 2018-08-02 03:30:00          93.0      ID32  2018-08-02  03:30:00
14 2018-08-02 03:45:00          88.0      ID32  2018-08-02  03:45:00
15 2018-08-02 04:00:00          80.0      ID32  2018-08-02  04:00:00
16 2018-08-02 04:15:00          90.0      ID32  2018-08-02  04:15:00
17 2018-08-02 04:30:00          99.0      ID32  2018-08-02  04:30:00
18 2018-08-02 04:45:00          89.0      ID32  2018-08-02  04:45:00
19 2018-08-02 05:00:00          85.0      ID32  2018-08-02  05:00:00
20 2018-08-02 05:15:00          75.0      ID32  2018-08-02  05:15:00
21 2018-08-02 05:30:00          84.0      ID32  2018-08-02  05:30:00
22 2018-08-02 05:45:00          89.0      ID32  2018-08-02  05:45:00
23 2018-08-02 06:00:00          90.0      ID32  2018-08-02  06:00:00
24 2018-08-02 06:15:00         114.0      ID32  2018-08-02  06:15:00
25 2018-08-02 06:30:00         163.0      ID32  2018-08-02  06:30:00
26 2018-08-02 06:45:00         193.0      ID32  2018-08-02  06:45:00
27 2018-08-02 07:00:00         158.0      ID32  2018-08-02  07:00:00
28 2018-08-02 07:15:00         122.0      ID32  2018-08-02  07:15:00
29 2018-08-02 07:30:00          84.0      ID32  2018-08-02  07:30:00
30 2018-08-02 07:45:00          79.0      ID32  2018-08-02  07:45:00
31 2018-08-02 08:00:00          72.0      ID32  2018-08-02  08:00:00
32 2018-08-02 08:15:00          91.0      ID32  2018-08-02  08:15:00
33 2018-08-02 08:30:00          99.0      ID32  2018-08-02  08:30:00
34 2018-08-02 08:45:00          99.0      ID32  2018-08-02  08:45:00
35 2018-08-02 09:00:00          92.0      ID32  2018-08-02  09:00:00
36 2018-08-02 09:15:00         104.0      ID32  2018-08-02  09:15:00
37 2018-08-02 09:30:00         109.0      ID32  2018-08-02  09:30:00
38 2018-08-02 09:45:00          94.0      ID32  2018-08-02  09:45:00
39 2018-08-02 10:00:00          89.0      ID32  2018-08-02  10:00:00
40 2018-08-02 10:15:00         104.0      ID32  2018-08-02  10:15:00
41 2018-08-02 10:30:00         133.0      ID32  2018-08-02  10:30:00
42 2018-08-02 10:45:00         146.0      ID32  2018-08-02  10:45:00
43 2018-08-02 11:00:00         136.0      ID32  2018-08-02  11:00:00
44 2018-08-02 11:15:00         114.0      ID32  2018-08-02  11:15:00
45 2018-08-02 11:30:00          96.0      ID32  2018-08-02  11:30:00
46 2018-08-02 11:45:00          97.0      ID32  2018-08-02  11:45:00
47 2018-08-02 12:00:00         111.0      ID32  2018-08-02  12:00:00
48 2018-08-02 12:15:00         114.0      ID32  2018-08-02  12:15:00
49 2018-08-02 12:30:00         116.0      ID32  2018-08-02  12:30:00
50 2018-08-02 12:45:00         107.0      ID32  2018-08-02  12:45:00
51 2018-08-02 13:00:00         115.0      ID32  2018-08-02  13:00:00

In [69]:
day = xx['Date'].iloc[-1]-xx['Date'].iloc[0]
day = day.days
day

0

In [71]:
Modd =0
s = 0
gvDiff = 0

if day<1:
    gvDiff = xx['GlucoseValue'] - xx['GlucoseValue'].shift(-1)
    s = round(gvDiff.sum(),3)
    Modd+=s
    print(Modd)
else:
    for Time, df in xx.groupby('Time'):
        gvDiff = df['GlucoseValue'] - df['GlucoseValue'].shift(-1)
        s = round(gvDiff.sum(),3)
        Modd+=s
    print(Modd/day)

-34.0